package lk.edu.javainstitute.studentclient.db;
// Generated Mar 31, 2016 12:59:48 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    ,catalog="studentapp"
)
public class Contact  implements java.io.Serializable {


     private Integer idContact;
     private String name;
     private String contact1;
     private String contact2;

    public Contact() {
    }

    public Contact(String name, String contact1, String contact2) {
       this.name = name;
       this.contact1 = contact1;
       this.contact2 = contact2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idContact", unique=true, nullable=false)
    public Integer getIdContact() {
        return this.idContact;
    }
    
    public void setIdContact(Integer idContact) {
        this.idContact = idContact;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="contact1")
    public String getContact1() {
        return this.contact1;
    }
    
    public void setContact1(String contact1) {
        this.contact1 = contact1;
    }

    
    @Column(name="contact2")
    public String getContact2() {
        return this.contact2;
    }
    
    public void setContact2(String contact2) {
        this.contact2 = contact2;
    }




}


