package lk.edu.javainstitute.studentclient.db;
// Generated Mar 31, 2016 12:59:48 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name="events"
    ,catalog="studentapp"
)
public class Events  implements java.io.Serializable {


     private Integer idevents;
     private String eventname;
     private String description;

    public Events() {
    }

    public Events(String eventname, String description) {
       this.eventname = eventname;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idevents", unique=true, nullable=false)
    public Integer getIdevents() {
        return this.idevents;
    }
    
    public void setIdevents(Integer idevents) {
        this.idevents = idevents;
    }

    
    @Column(name="eventname")
    public String getEventname() {
        return this.eventname;
    }
    
    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


