package lk.edu.javainstitute.studentclient.db;
// Generated Mar 31, 2016 12:59:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stdent generated by hbm2java
 */
@Entity
@Table(name="stdent"
    ,catalog="studentapp"
)
public class Stdent  implements java.io.Serializable {


     private String nic;
     private String studName;
     private Set<Marks> markses = new HashSet<Marks>(0);

    public Stdent() {
    }

	
    public Stdent(String nic) {
        this.nic = nic;
    }
    public Stdent(String nic, String studName, Set<Marks> markses) {
       this.nic = nic;
       this.studName = studName;
       this.markses = markses;
    }
   
     @Id 

    
    @Column(name="NIC", unique=true, nullable=false)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }

    
    @Column(name="stud_name")
    public String getStudName() {
        return this.studName;
    }
    
    public void setStudName(String studName) {
        this.studName = studName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stdent")
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }




}


