package lk.edu.javainstitute.studentclient.db;
// Generated Mar 31, 2016 12:59:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name="subject"
    ,catalog="studentapp"
)
public class Subject  implements java.io.Serializable {


     private Integer idsubject;
     private Year year;
     private String subject;
     private Set<Marks> markses = new HashSet<Marks>(0);

    public Subject() {
    }

	
    public Subject(Year year) {
        this.year = year;
    }
    public Subject(Year year, String subject, Set<Marks> markses) {
       this.year = year;
       this.subject = subject;
       this.markses = markses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idsubject", unique=true, nullable=false)
    public Integer getIdsubject() {
        return this.idsubject;
    }
    
    public void setIdsubject(Integer idsubject) {
        this.idsubject = idsubject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="year_idyear", nullable=false)
    public Year getYear() {
        return this.year;
    }
    
    public void setYear(Year year) {
        this.year = year;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }




}


